/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_akhir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author zeroo
 */
public class admin extends javax.swing.JFrame {
     Connection koneksi;
     private String pilihan;

    /**
     * Creates new form profil
     */
    public admin() {
        initComponents();
        koneksi = database.getConnection(); //inisialisasi database

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxGame = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        fdiamond_100000 = new javax.swing.JTextField();
        fdiamond_100 = new javax.swing.JTextField();
        fdiamond_1000 = new javax.swing.JTextField();
        fdiamond_10000 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Selamat Datang dihalaman admin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Edit harga diamond 100 000");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        comboBoxGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilihlah game----", "Free Fire", "Mobile Legend", "Call Of Duty", "Clash Of Clans", "AOV", "PUBG" }));
        comboBoxGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGameActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 374, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, -1, -1));
        jPanel1.add(fdiamond_100000, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 370, -1));
        jPanel1.add(fdiamond_100, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 370, -1));
        jPanel1.add(fdiamond_1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 370, -1));
        jPanel1.add(fdiamond_10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 370, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Anda dapat mengedit data haga diamond disini");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 56, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Edit harga diamond 100");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Edit harga diamond 1000");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Edit harga diamond 10 000");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        loadDataUpdateAdmin();
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void comboBoxGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGameActionPerformed
        // TODO add your handling code here:
        
    String selectedGame = (String) comboBoxGame.getSelectedItem();
    switch (selectedGame) {
        case "Free Fire":
            pilihan = "freefire";
            break;
        case "Mobile Legend":
            pilihan = "mobilelegend";
            break;
        case "PUBG":
            pilihan = "pubg";
            break;
        case "AOV":
            pilihan = "aov";
            break;
        case "Clash Of Clans":
            pilihan = "clashofclans";
            break;
        case "Call Of Duty":
            pilihan = "callofduty";
            break;
            
            
        // Tambahkan case lain sesuai kebutuhan
        default:
            pilihan = null; // Jika tidak ada yang cocok
            break;
    }
    System.out.println("Pilihan: " + pilihan); // Untuk debugging
                                      
        
        
        
    }//GEN-LAST:event_comboBoxGameActionPerformed

    
    

    
    private void loadDataUpdateAdmin() {

        int nilai100diamond = Integer.valueOf(fdiamond_100.getText());
        int nilai1000diamond = Integer.valueOf(fdiamond_1000.getText());
        int nilai10000diamond = Integer.valueOf(fdiamond_10000.getText());
        int nilai100000diamond = Integer.valueOf(fdiamond_100000.getText());
      


        
        
        String sql = "UPDATE harga_game SET diamond_100 = ?, diamond_1000 = ?, diamond_10000 = ?, diamond_100000= ? WHERE nama_game = ?";
        
        
        try {
            PreparedStatement ps = koneksi.prepareStatement(sql);
            ps.setInt(1, nilai100diamond);    // Ganti dengan nilai yang sesuai untuk 100diamond
            ps.setInt(2, nilai1000diamond);   // Ganti dengan nilai yang sesuai untuk 1000diamond
            ps.setInt(3, nilai10000diamond);  // Ganti dengan nilai yang sesuai untuk 10000diamond
            ps.setInt(4, nilai100000diamond); // Ganti dengan nilai yang sesuai untuk 100000diamond
            ps.setString(5, pilihan);         // Pastikan 'pilihan' berisi nama game yang ingin diupdate
        
        // Eksekusi update
        int rowsUpdated = ps.executeUpdate();
        if (rowsUpdated > 0) {
            System.out.println("Data berhasil diupdate.");
        } else {
            System.out.println("Tidak ada data yang diupdate.");
        }
        } catch (SQLException e) {
            System.out.println("terjadi kesalahan: " + e.getMessage());
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxGame;
    private javax.swing.JTextField fdiamond_100;
    private javax.swing.JTextField fdiamond_1000;
    private javax.swing.JTextField fdiamond_10000;
    private javax.swing.JTextField fdiamond_100000;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
