/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_akhir;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author zeroo
 */
public class profil extends javax.swing.JFrame {

    Connection koneksi;
    private String NamaUserProfil;
    private String nama_user;

    /**
     * Creates new form profil
     */
    public profil() {
        initComponents();
        
        koneksi = database.getConnection(); //inisialisasi database
        loadDataLoginprofil();

    }

    public void setNamaUserProfil(String username) {
        this.NamaUserProfil = username;

    }

    //load data login
    private void loadDataLoginprofil() {

        
        
        String sql = "SELECT nama_user FROM user WHERE username = ?";
        try {
            PreparedStatement ps = koneksi.prepareStatement(sql);
            ps.setString(1, NamaUserProfil);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                nama_user = rs.getString("nama_user");
                profilout.setText(nama_user);

            }

        } catch (SQLException e) {
            System.out.println("terjadi kesalahan: " + e.getMessage());
        }
    }
    
    
    private void updateDataLoginprofil() {
        String ubah_nama = fubahnama.getText();
        if (ubah_nama== null || ubah_nama.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Silahkan isi nama pengguna dulu");
        return; // Hentikan eksekusi jika NamaUserProfil kosong
             }
        
    // Prepare update query with username as where clause
    String sql = "UPDATE user SET nama_user = ? WHERE username = ?";

    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        ps.setString(1, ubah_nama); // Set new name
        ps.setString(2, NamaUserProfil); 

        int rowsUpdated = ps.executeUpdate();

        if (rowsUpdated > 0) {
//            System.out.println("Nama pengguna berhasil diperbarui.");
        } else {
            System.out.println("Tidak ada perubahan yang dilakukan (username mungkin tidak ditemukan).");
        }
    } catch (SQLException e) {
        System.out.println("Error updating data: "  + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profilout = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        redfresh = new javax.swing.JButton();
        fubahnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        updatee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek_akhir/images/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 203));

        profilout.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        profilout.setText("Your Name");
        jPanel1.add(profilout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        redfresh.setText("Refresh");
        redfresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redfreshActionPerformed(evt);
            }
        });
        jPanel1.add(redfresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        fubahnama.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jPanel1.add(fubahnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 290, 30));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("Masukkan Nama Baru");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        updatee.setText("update");
        updatee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateeActionPerformed(evt);
            }
        });
        jPanel1.add(updatee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_keluarActionPerformed

    private void redfreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redfreshActionPerformed
        // TODO add your handling code here:
        loadDataLoginprofil();

    }//GEN-LAST:event_redfreshActionPerformed

    private void updateeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateeActionPerformed
        // TODO add your handling code here:
        updateDataLoginprofil();
    }//GEN-LAST:event_updateeActionPerformed

//    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
//         
//        // Set parameter query (pilihan game)
//        ps.setString(1, "mobilelegend");
//        
//        ResultSet rs = ps.executeQuery();
//        
//        if (rs.next()) {
//            // Ambil nilai harga dari hasil query
//            int diamond100 = rs.getInt("diamond_100");
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fubahnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel profilout;
    private javax.swing.JButton redfresh;
    private javax.swing.JButton updatee;
    // End of variables declaration//GEN-END:variables
}
